version: '3.8'

volumes:
  database:

services:
  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=alicedb'
      - 'MARIADB_PASSWORD=test123'
      - 'MARIADB_ROOT_PASSWORD=test123'
      - 'MARIADB_USER=root'
    ports:
      - '3306'
    volumes:
      - database:/var/lib/mysql
